### ISSUE TITLE
Says I need a valid .env config

### ISSUE THREAD

**Issue by ziotVFX** [FrozenTear7/twitch-spambot#5]
**Describe the bug**

**To Reproduce**
2. Run script '...'
3. See error

**Expected behavior**
I expected for it to work
![Screenshot (11)](https://user-images.githubusercontent.com/79606421/109248708-4af01a00-77b4-11eb-9b22-026bf756af30.png)

(i also made a .env file)

**Comment by FrozenTear7** [comment]
Config variables are read from the `.env` file as shown below:

https://github.com/FrozenTear7/twitch-spambot/blob/1f065ab1044ab86653d3c67fca7de4220905ab43/config/config.js#L7-L12

so the only problem here could be misspelling on your part or Repl.it not reading the file properly, According to their docs though, `.env` file works fine just like anywhere else so please make sure the format of your `.env` file is correct.
Here is an example of how a config should look like:

```
TWITCH_USERNAME=RandomUsername
CLIENT_TOKEN=oauth:d67217d872yha8d2a97d9a298e1f1
```

where you should put your correct values on the right side of the assignment `=`.
You can generate your Client token [here](https://twitchapps.com/tmi/).

Also make sure to put your `.env` file into the root directory of the project, otherwise it will not be seen.

**Comment by FrozenTear7** [comment]
I'm closing this issue due to no response.
If the problem persists, please try the newly released version as it's tested to be working properly.
